-- 兑换码表
CREATE TABLE IF NOT EXISTS `redeem_code` (
  `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `code` VARCHAR(32) NOT NULL UNIQUE COMMENT '兑换码',
  `amount` INT NOT NULL DEFAULT 0 COMMENT '兑换次数',
  `used` TINYINT NOT NULL DEFAULT 0 COMMENT '是否已使用',
  `used_device_id` VARCHAR(64) DEFAULT NULL COMMENT '使用的设备ID',
  `used_at` DATETIME DEFAULT NULL COMMENT '使用时间',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='兑换码表';